ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS logo_url TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS favicon_url TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS primary_color TEXT DEFAULT '174 72% 50%',
  ADD COLUMN IF NOT EXISTS accent_color TEXT DEFAULT '199 89% 48%',
  ADD COLUMN IF NOT EXISTS background_color TEXT DEFAULT '222 47% 6%';